package tests;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Vector;

import cmsc433.Machines;
import cmsc433.SimulationEvent;

/**
 * Validates a simulation
 */
public class GraderValidate {

	/**
	 * Validates the given list of events is a valid simulation.
	 * Returns true if the simulation is valid, false otherwise.
	 *
	 * @param events - a list of events generated by the simulation
	 *        in the order they were generated.
	 *
	 * @returns res - whether the simulation was valid or not
	 */

	public static boolean validateSimulation(List<SimulationEvent> events) {
		//verify the events here
		return true;
	}
}
